import json
import uuid
from pathlib import Path
from typing import Any, Dict, List

from jinja2 import Environment, FileSystemLoader, select_autoescape

from .config import Settings, get_settings
from .db import insert_report, list_rows
from .scanners import finding_to_public_dict


def build_report(scan_id: str, settings: Settings = None) -> Dict[str, Any]:
    settings = settings or get_settings()
    settings.report_dir.mkdir(parents=True, exist_ok=True)

    scan = list_rows("SELECT * FROM scans WHERE id = ?", (scan_id,))[0]
    findings = [
        finding_to_public_dict(row)
        for row in list_rows("SELECT * FROM findings WHERE scan_id = ? ORDER BY created_at", (scan_id,))
    ]
    risk_score = _risk_score(findings)
    report_id = f"RPT-{uuid.uuid4().hex[:12].upper()}"
    title = f"{scan['type'].title()} Security Report"
    summary = f"{len(findings)} findings generated by AI2Sec safe MVP pipeline."

    payload = {
        "id": report_id,
        "scanId": scan_id,
        "title": title,
        "scanType": scan["type"],
        "target": scan["target"] or scan["project_name"],
        "riskScore": risk_score,
        "summary": summary,
        "findings": findings,
    }

    markdown = _render_markdown(payload)
    markdown_path = settings.report_dir / f"{report_id}.md"
    json_path = settings.report_dir / f"{report_id}.json"
    markdown_path.write_text(markdown, encoding="utf-8")
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    insert_report(
        {
            "id": report_id,
            "scan_id": scan_id,
            "title": title,
            "risk_score": risk_score,
            "summary": summary,
            "markdown_path": str(markdown_path),
            "json_path": str(json_path),
        }
    )
    return payload


def public_report(row: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "id": row["id"],
        "scanId": row["scan_id"],
        "title": row["title"],
        "riskScore": row["risk_score"],
        "summary": row["summary"],
        "createdAt": row["created_at"],
    }


def _render_markdown(payload: Dict[str, Any]) -> str:
    template_dir = Path(__file__).parent / "templates"
    env = Environment(
        loader=FileSystemLoader(template_dir),
        autoescape=select_autoescape(enabled_extensions=()),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    return env.get_template("report.md.j2").render(report=payload)


def _risk_score(findings: List[Dict[str, Any]]) -> float:
    weights = {"critical": 10.0, "high": 8.0, "medium": 5.0, "low": 2.0}
    if not findings:
        return 0.0
    return round(min(10.0, sum(weights.get(item["severity"], 1.0) for item in findings) / 2.0), 1)
